project:
  type: website
  output-dir: docs
# ~ additional metadata excluded for brevity ~
  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true


website:
  title: "lktuan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    fontsize: 1.1em
    theme: 
      - inception
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true

editor: visual

execute:
  freeze: auto
  


