author-name: "Le Khac Tuan"
draft: false

project:
  type: website
  output-dir: docs

  resources:
    - "img/**"
    - "assets/**"
    - commit_info.js
    # - "sitemap.xml"
    # - "_redirects"

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

render:
  - "*.qmd"
  - "*.md"
  - "!etc/"
  - "!assets/"

title-meta: "Le Khac Tuan"
description-meta: "This is Tuan's blog"

website:
  title: "Le Khac Tuan"
  description: "This is Tuan's blog"
  site-url: "https://lktuan.github.io/"
  
  repo-url: "https://github.com/lktuan/lktuan.github.io"
  repo-branch: main

  favicon: img/rocket_1613268.png

  # start of the navigation bar at the top of the website
  navbar:
    pinned: true

    left:
      - text: "About"
        href: about/index.qmd
      - text: "Curriculum"
        href: curriculum/index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "学汉语的日记"
        href: 学汉语的日记.qmd
      - text: "Jiu Jitsu Journal"
        href: jiu_jitsu_journal/index.qmd

    # your social media handles
    right:
      - icon: github
        # text: Github
        href: https://github.com/lktuan
      - icon: linkedin
        # text: LinkedIn
        href: https://www.linkedin.com/in/tuanlekhac/
      - icon: facebook
        # text: Facebook
        href: https://www.facebook.com/toilatuan.lk/
      - icon: twitter-x
        # text: X
        href: https://x.com/Halle4231
      - icon: envelope
        # text: Email
        href: "mailto:tuan.lekhac0905@gmail.com"   

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox

  page-footer: 
    left: |
      <span class="faux-block">[{{< fa brands creative-commons >}}](https://creativecommons.org/licenses/by-nc-nd/4.0/) 2023-2025 Le Khac Tuan</span>
    center: |
      <span class="faux-block">
        Designed with {{< fa heart >}}, <span id="commit-info">Loading last commit...</span>
      </span>
    right: |
      <span class="faux-block">Made with [Quarto](https://quarto.org/)</span>

format:
  html:
    fontsize: 1.0em
    grid: 
      body-width: 900px
    theme: 
      # - html/styles.scss
      light: simplex
      dark: superhero
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: bottom
    reference-location: margin
    footnotes-hover: true
    highlight-style: gruvbox
    code-overflow: scroll

    include-after-body:
      text: |
        <script type="application/javascript" src="commit_info.js"></script>


editor: source

execute:
  freeze: true
  