author-name: "Le Khac Tuan"
draft: false


project:
  type: website
  output-dir: docs

  resources:
    - "img/**"
    - "assets/**"
    # - "sitemap.xml"
    # - "_redirects"

  # ~ additional metadata excluded for brevity ~
  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

render:
  - "*.qmd"
  - "*.md"
  - "!etc/"

title-meta: "Le Khac Tuan"
description-meta: "I am a Risk Modeler 🚀"

website:
  title: "Le Khac Tuan" # This is my name
  description: "I am a Risk Modeler 🚀" # A brief slogan
  site-url: "https://lktuan.github.io/"
  
  repo-url: "https://github.com/lktuan/lktuan.github.io"
  repo-branch: main

  favicon: img/rocket_1613268.png

  # start of the navigation bar at the top of the website
  navbar:
    pinned: true

    left:
      - text: "About"
        href: about/index.qmd
      - text: "Curriculum"
        href: curriculum/index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "学汉语的日记"
        href: 学汉语的日记.qmd
      - text: "Jiu Jitsu Journal"
        href: jiu_jitsu_journal/index.qmd

    # your social media handles
    right:
      # - icon: twitter
      #   # text: Twitter
      #   href: https://twitter.com/Halle4231
      - icon: github
        # text: Github
        href: https://github.com/lktuan
      - icon: linkedin
        # text: LinkedIn
        href: https://www.linkedin.com/in/tuanlekhac/
      - icon: facebook
        # text: Facebook
        href: https://www.facebook.com/toilatuan.lk/
      - icon: envelope
        # text: Email
        href: "mailto:tuan.lekhac0905@gmail.com"   


# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox

  # page-footer: 
  #   left: "Build with {{< fa heart >} and [Quarto](https://quarto.org/), by Tuan Le Khac (2023-204). License [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)"
  #   right: "[View the source at {{< fa brands github >}} GitHub](https://github.com/lktuan/lktuan.github.io)"

  page-footer: 
    left: |
      <span class="faux-block">[{{< fa brands creative-commons >}}](https://creativecommons.org/licenses/by-nc-nd/4.0/) 2023-2024 Le Khac Tuan</span>

    center: |
      <span class="faux-block">Designed with {{< fa heart >}}</span>
    right: |
      <span class="faux-block">Made with [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub](https://github.com/lktuan/lktuan.github.io)</span>





format:
  html:
    fontsize: 1.0em
    grid: 
      body-width: 900px
    theme: 
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: bottom
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai

editor: visual

execute:
  freeze: true
  