project:
  type: website
  output-dir: docs
# ~ additional metadata excluded for brevity ~

website:
  title: "lktuan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
  


