---
title: "Curriculum Vitae" # Curriculum vitae
title-block-banner: true
format:
    html:
        code-tools: true
toc: true
toc-location: right
---

# **Summary**

Results-driven data analyst with extensive experience in risk management and SME lending, backed by a foundation in external audit and corporate finance. Proven expertise in developing credit risk models, portfolio analytics, and data-driven solutions. Seeking to leverage advanced analytics capabilities and banking domain knowledge to drive strategic risk management decisions as well as new challenges in others domain: e-commerce, insurance, manufacturing.

Interested topics:

-   Deep credit risk analytics (Basel, CECL, IFRS 9);
-   Bayesian Modeling;
-   Causal Inference;
-   Advanced visualization (grammar of graphics, ICBS standard).

This is my curriculum vitae, for a one-pager profile please refer to my [résumé](https://lktuan.github.io/curriculum/resume/).

# **Career**

------------------------------------------------------------------------

### [VGrowth Development Co.,Ltd](https://validus.vn/)

**Risk Management (Mar, 23 - present)**

I worked as a Senior Data Analyst:

-   Lead end-to-end credit analytics initiatives covering underwriting, portfolio management, and collections, resulting in optimized credit policies and risk controls;
-   Develop and implement an application scorecard for MSMEs/Households lending products, collaborating closely with CRO/CDO throughout the model lifecycle;
-   Manage data curation, warehousing, and reporting workflows to support operation and reporting system;
-   Streamline cross-functional processes across Sales, Product, Underwriting, Collection, Finance, and Operations teams through data-driven solutions,implementing KPIs and customer segmentation frameworks to enhance automation and operational efficiency.

### [VietCredit Finance Company](https://www.vietcredit.com.vn/)

**Risk Management (Feb, 22 - Mar, 23)**

I worked as a Data Analyst:

-   Conducted comprehensive portfolio quality analyses and product reporting, delivering actionable recommendations for product policy and risk control;
-   Managed data curation and reporting workflows for critical daily/monthly deliverables while contributing to enterprise data projects;
-   Participated in company’s digital transformations projects, monitored UAT for new applications, assisted others departments on daily operation.

### [Techtronic Industries Vietnam Mfg. Co., Ltd](https://www.ttigroup.com.vn/)

**Operation Finance (Jan, 21 - Feb, 22)**

I worked as a Financial Analyst:

-   Partnered with Production teams to ensure data accuracy and generate efficiency reports for Vietnam factories;
-   Prepared monthly functional P&L, directly handled accrual, analysis, forecast, & budget preparation for Direct Labor;
-   Performed cost control in the belt-tightening period due to the Covid pandemic, co-operated effectively with other functional departments for daily operation process.

### [Ernst & Young Vietnam Ltd](https://www.ey.com/)

**Core Assurance (Dec, 19 - Jan, 21)**

I worked as an Audit Assistant:

-   Interviewed client, evaluated control environment from the critical understanding of the business process, defined possibility of accounting material misstatements;
-   Executed risk-based audit procedures following EY methodology to verify financial statement accuracy;
-   Supported senior management in financial statement preparation and issuance.

# **Education**

------------------------------------------------------------------------

### [Foreign Trade University, HCMC campus](https://cs2.ftu.edu.vn/)

**Bachelor of Accounting & Auditing (Dec, 16 - Apr, 20)**

-   GPA: 8.4/10 (3.41/4)
-   Graduation thesis: 8.9/10 (“Accounting information quality, information asymmetry, and the cost of capital” - used R & Stata for data crawling, manipulation, and modeling).

### [Phan Boi Chau High School for the Gifted](https://www.linkedin.com/company/phan-boi-chau-high-shool-for-the-gifted/about/)

**Math Specilized Class (Dec, 13 - May, 16)**

# **Technical Skills**

------------------------------------------------------------------------

-   **Domain Expertise**: Credit risk analytics • Customer segmentation • Product pricing • Financial analysis
-   **Data Processing**: Salesforce • Excel & Power Query • Google Sheets & Apps Script • Pandas • dplyr
-   **Visualization/Presentation**: Excel & Powerpoint • Power BI • Ggplot2 • R Markdown & Quarto
-   **Modeling**: Power Pivot & Power BI • scikit-learn • statsmodels
-   **Programming**: Python • R • SQL • PowerShell/Bash • Git

# **Languages**

------------------------------------------------------------------------

Vietnamese (native language) • English (fluent in communication) • Chinese Mandarin (HSK 5 equivalent).

Please also visit my [GitHub](https://github.com/lktuan) for the projects I did and visit my [Linked in](https://www.linkedin.com/in/tuanlekhac/) for more details.