---
title: "Một số khuôn mẫu tư duy trong Brazilian Jiu-jitsu"
description: 'a quick and short note on "Mechanic Models of BJJ: A Crash Course" by Steve Kwan'
author:
  - name: "Tuan Le Khac"
    url: https://lktuan.github.io/
categories: [bjj] 
date: 08-06-2024
date-modified: 08-06-2024
---

# 1. theory of alighment

1. posture:
2. structure:
3. base:

1. maintain your alignment;
2. break your opponent's alignment;
3. do not proceed 2. if you are failing at 1.


# 2. core mechanics

1. frame:
2. levers:
3. wedges:
4. clamps:
5. hooks:
6. posts:

# 3. anatomic hierarchy

human body has 6 areas

1. core;
2. 2 legs;
3. 2 arms;
4. head.

# 4. type of guards

1. hook-based;
2. clamp-based;
3. frame-based;
4. hybrid.

# 5. breaking mechanics

1. isolate a lever:
2. prevent predictable defenses;
3. maximize leverage;
4. apply overwhelming force.

# 6. choking mechanics

1. air chokes:
2. blood chokes;
3. cranks;
4. compression chokes;
5. hybrid chokes.

# 7. ratchet control

# 8. controlled breathing

# 9. staying loose

# 10. limd coiling

# 11. elbow-knee connection

# 12. solid frames

# 13. kinetic chains

# 14. body tethering

# 15. inside channel control

# 16. single vs. double level control

# 17. overwhelming force

# 18. surface area